# Generated by Django 5.2.1 on 2025-05-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_project_options_alter_project_image'),
        ('portafolio', '0002_alter_project_options_project_link_and_more'),
    ]

    operations = [
    ]
